### ISSUE TITLE
Does not work on mobile Twitter

### ISSUE THREAD

**Issue by AhmedYasinKUL** [Flkalas/TwitterVideoAssistChrome#2]
Hi,

I'm using Google Chrome extensions on my Android telephone by using Yandex Browser. Your extension is working on desktop version of Twitter but download button is not shown on mobile version of Twitter. So, could you please add support for mobile version of Twitter so that download button will be shown? Thanks.

**Comment by Flkalas** [comment]
I seem to that you use mobile.twitter.com in Yandex Browser. Twitter has a same interface mobile sub-domain and main domain at these days. So I add an address of the mobile Twitter in the manifest. Now the client script would be act mobile Twitter, and you could download Twitter media. If not works, please reopen this issue. Thanks.
